### ISSUE TITLE
C# SDK - Acesso aos dados do cartão - versão 3.12.0

### ISSUE THREAD

**Issue by rguedes** [amagovpt/autenticacao.gov#164]
Depois de actualizar para versão 3.12.0 deixei de conseguir aceder aos dados do cartão.

Na minha aplicação aparece o seguinte erro:

``
  Unhandled exception occurred while executing request: Error while retrieving card data.
       ---> System.EntryPointNotFoundException: Unable to find an entry point named 'CSharp_ptfportugalfeid_PTEID_XMLDoc_SWIGUpcast___' in DLL 'pteidlibCS_Wrapper'.
         at pt.portugal.eid.pteidlib_dotNetPINVOKE.PTEID_XMLDoc_SWIGUpcast(IntPtr jarg1)
         at pt.portugal.eid.PTEID_XMLDoc..ctor(IntPtr cPtr, Boolean cMemoryOwn)
         at pt.portugal.eid.PTEID_EId..ctor(IntPtr cPtr, Boolean cMemoryOwn)
         at pt.portugal.eid.PTEID_EIDCard.getID()

``

Fizeram alguma alteração ao SDK ? Será por causa do Contactless?

**Comment by rguedes** [comment]
Já descobri e resolvi.

é um destes 3 campos:
  TaxNumber = eid.getTaxNo(),
  HealthNumber = eid.getHealthNumber(),
  SocialSecurityNumber = eid.getSocialSecurityNumber(),
