### ISSUE TITLE
Exceção "System.DllNotFoundException: pteidlibCS_Wrapper"

### ISSUE THREAD

**Issue by renatolopeslatitudde** [amagovpt/autenticacao.gov#168]
Boa tarde, estamos a tentar desenvolver uma aplicação que usar c# na tecnologia blazor e que utiliza dotnet 8.
Foi feito o import de "pteidlib_dotnet.dll" tanto na versão 3.12 como 3.11 e em ambos os casos quando tento inicializar o sdk ("		private async Task SignPDF()
		{
			try
			{
				PTEID_ReaderSet.initSDK();")

ele dá a seguinte exceção "System.TypeInitializationException: The type initializer for 'pt.portugal.eid.pteidlib_dotNetPINVOKE' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
 ---> System.DllNotFoundException: pteidlibCS_Wrapper
   at pt.portugal.eid.pteidlib_dotNetPINVOKE.SWIGExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at pt.portugal.eid.pteidlib_dotNetPINVOKE..cctor()
   --- End of inner exception stack trace ---
   at pt.portugal.eid.PTEID_ReaderSet.initSDK()"
   
 É necessário realizar mais algum import ou utilizar o pteidlibCS_Wrapper de alguma maneira?

Com os melhores cumprimentos.

**Comment by renatolopeslatitudde** [comment]
O problema estava relacionado com ser Blazor WebAssembly, já que o dll não consegue ter comunicação com o programa instalado no desktop.
Alguma alternativa ou maneira de conseguir estabelecer comunicação do browser com sdk e seguidamente com o leitor de cartões?
