### ISSUE TITLE
Erro ao carregar a biblioteca

### ISSUE THREAD

**Issue by diogocarreirarxi** [amagovpt/autenticacao.gov#175]
Bom dia,

Eu usei o vosso SDK para ler informaçao do cartao numa  aplicaçao em java ubuntu, estou a executar atraves de um .jar.

Funcionou bem (3.11.0) ate a nova atualizaçao para windows (3.12.0).

Em linux se eu eu especificar o caminho da biblioteca (-Djava.library.path=/usr/local/lib/) atraves da linha de comandos ou correr um script com esse path ele funciona.

Mas em windows desde essa atualizaçao nao consigo colocar a funcionar nem com um .bat script com o path(java -D"java.library.path"="C:\Program Files\PortugalIdentity Card\sdk) nem ao adicionar o path para executar o .jar na linha de comandos.

SE fizer duplo clique no ficheiro .jar da este erro: 

Received request to read card.
Valid token, proceeding with card reading.
2024-07-29T12:51:42.181+01:00 ERROR 7244 --- [CardRead_Project] [nio-8018-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed: java.lang.UnsatisfiedLinkError: 'long pt.gov.cartaodecidadao.pteidlibJava_WrapperJNI.PTEID_XMLDoc_SWIGUpcast(long)'] with root cause

java.lang.UnsatisfiedLinkError: 'long pt.gov.cartaodecidadao.pteidlibJava_WrapperJNI.PTEID_XMLDoc_SWIGUpcast(long)'
	at pt.gov.cartaodecidadao.pteidlibJava_WrapperJNI.PTEID_XMLDoc_SWIGUpcast(Native Method) ~[pteidlibj-1.0.jar!/:na]
	at pt.gov.cartaodecidadao.PTEID_XMLDoc.<init>(PTEID_XMLDoc.java:18) ~[pteidlibj-1.0.jar!/:na]
	at pt.gov.cartaodecidadao.PTEID_EId.<init>(PTEID_EId.java:19) ~[pteidlibj-1.0.jar!/:na]
	at pt.gov.cartaodecidadao.PTEID_EIDCard.getID(PTEID_EIDCard.java:51) ~[pteidlibj-1.0.jar!/:na]
	at com.example.CardRead_Project.GetXML.initiate(GetXML.java:46) ~[!/:0.0.1-SNAPSHOT]
	at com.example.CardRead_Project.GetXML.start(GetXML.java:124) ~[!/:0.0.1-SNAPSHOT]
	at com.example.CardRead_Project.CardInfoServer.readCard(CardInfoServer.java:28) ~[!/:0.0.1-SNAPSHOT]

Como funciona na versao 3.11.0, gostaria de saber o que esta em falta para funcionar, se foi alterada a biblioteca com a versao 3.12.0 ou o caminho dela.

**Comment by agrr** [comment]
Bom dia,

Parece ser uma questão idêntica à do issue #166 
A versão da `pteidlibj.jar` que está na classpath da aplicação deve ser a que é distribuída com o Autenticação.gov 3.12.0.
