### ISSUE TITLE
Novos CC: java.security.InvalidKeyException: Not an RSA key: EC

### ISSUE THREAD

**Issue by AndreasPilgrim** [amagovpt/autenticacao.gov#185]
Boa tarde,

Aquando de assinatura digital com SDK Java com um novo Cartão de Cidadão, recebo a exception:

java.security.InvalidKeyException: Not an RSA key: EC
        at sun.security.rsa.RSAKeyFactory.engineTranslateKey(Unknown Source)
        at sun.security.rsa.RSAKeyFactory.toRSAKey(Unknown Source)
        at sun.security.rsa.RSASignature.engineInitSign(Unknown Source)
        at sun.security.rsa.RSASignature.engineInitSign(Unknown Source)
        at java.security.Signature$Delegate.init(Unknown Source)
        at java.security.Signature$Delegate.chooseProvider(Unknown Source)
        at java.security.Signature$Delegate.engineInitSign(Unknown Source)
        at java.security.Signature.initSign(Unknown Source)
        at org.jcp.xml.dsig.internal.dom.DOMSignatureMethod.sign(Unknown Source)

O método de implementação da assinatura é com PKCS11 conforme o vosso manual.
Podem auxiliar?

**Comment by AndreasPilgrim** [comment]
Boa tarde,

Confirmo que da forma que mencionou já fica funcional.

Muito obrigado pelo auxílio.
