### ISSUE TITLE
Online Address: Timeout on address reading

### ISSUE THREAD

**Issue by suportecaso1** [amagovpt/autenticacao.gov#193]
Desde dia 27-dez que está a dar erro ao tentar obter moradas.
Online Address: Timeout on address reading
pt.gov.cartaodecidadao.PTEID_Exception
	at pt.gov.cartaodecidadao.pteidlibJava_WrapperJNI.PTEID_Address_getAbbrBuildingType(Native Method)
	at pt.gov.cartaodecidadao.PTEID_Address.getAbbrBuildingType(PTEID_Address.java:124)

**Comment by suportecaso1** [comment]
Após mais alguns testes, reparamos que este erro acontece tanto na versão 3.12 com 3.13 da Autenticação.gov.
Testamos com dois cartões (versões 006.005.23 e 006.008.34) e deu o erro referido no comentário anterior.
Testamos também com um cartão dos novos (versão 07.35), onde já foi possível obter a morada!

![2025-01-02_10-34](https://github.com/user-attachments/assets/bc1dd030-aed4-4cea-8231-6dea94ece715)

**Comment by agrr** [comment]
Bom dia,

está indisponível o serviço online que o SDK e a aplicação utilizam para consultar a morada dos cartões emitidos até junho de 2024. No caso dos cartões novos (CC2) é utilizado um serviço diferente.

Já alertámos os responsáveis, pedimos desculpa pelo incómodo.

**Comment by Peandreo** [comment]
Boa tarde,

existe alguma prvisão de quando o problema de leitura da morada o problema fique resolvido ?

Obrigado.

**Comment by agrr** [comment]
Boa tarde, 

já está disponível de novo o serviço de leitura de morada.

**Comment by Peandreo** [comment]
Boa tarde,

obrigado pela rapidez.

**Comment by suportecaso1** [comment]
Boa tarde,
obrigado pela resposta.

**Comment by suportecaso1** [comment]
Boa tarde,
obrigado pela resposta.
Sendo assim, está resolvida a questão.
