### ISSUE TITLE
Erro a iniciar SDK

### ISSUE THREAD

**Issue by joaogalaio** [amagovpt/autenticacao.gov#38]
Boa tarde.

Estou a usar o jar que veio na versão do 3.1.1 instalado através de deb para ubuntu 18. Ao iniciar o sdk em java, obtenho o seguinte erro:

Exception in thread "main" java.lang.UnsatisfiedLinkError: pt.gov.cartaodecidadao.pteidlibJava_WrapperJNI.PTEID_ReaderSet_initSDK__SWIG_1()V
	at pt.gov.cartaodecidadao.pteidlibJava_WrapperJNI.PTEID_ReaderSet_initSDK__SWIG_1(Native Method)
	at pt.gov.cartaodecidadao.PTEID_ReaderSet.initSDK(PTEID_ReaderSet.java:47)

        try
        {
            PTEID_ReaderSet.initSDK();
            PTEID_ReaderContext context = PTEID_ReaderSet.instance().getReader();

            // message to sign

**Comment by ACamposPT** [comment]
Bom dia,
Pedimos para verifique as instruções dos nossos manuais:

https://amagovpt.github.io/autenticacao.gov/manual_sdk.html

https://amagovpt.github.io/autenticacao.gov/sdk/java/

Nomeadamente a indicação "Make sure that the JNI library is explicitly loaded using the following code (this implements the wrapper functions for Java) "

Se continuar com problemas, volte a contactar.
